on:
  pull_request:
    branches:
    - master
  schedule:
  - cron: "0 12 * * *"
  workflow_dispatch:

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Send mail
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.gmail.com
          server_port: 465
          username: ${{secrets.MAIL_USERNAME}}
          password: ${{secrets.MAIL_PASSWORD}}
          subject: '[HelloTools Cloud] 您的验证码'
          # Optional HTML body read from file:
          html_body: file://otp.html
          to: ${{secrets.MAIL_TO}}
          from: HelloTools Cloud
          # Optional recipient of the email response:
          reply_to: hackpig520+cn@gmail.com
          priority: high
