on:
  pull_request:
    branches:
    - master
  workflow_dispatch:

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Send mail
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.gmail.com
          server_port: 465
          username: ${{secrets.MAIL_USERNAME}}
          password: ${{secrets.MAIL_PASSWORD}}
          subject: '[HelloTools Cloud] 您的今日任务运行成功'
          body: Build job of ${{github.repository}} completed successfully!
          to: ${{secrets.MAIL_TO}}
          from: HelloTools Cloud
          # Optional recipient of the email response:
          reply_to: hackpig520+cn@gmail.com
          priority: low
