on:
  push:
    branches:
    - master
  pull_request:
    branches:
    - master
  workflow_dispatch:
  schedule:
  - cron: "11 4 */7 * *"

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - name: 2M.PUB 域名续期
        run: |
          curl -s https://2m.statict.cn/ren?fqdn=chushengict.2m.pub&t=80a42e88d16a1446f5cf3832b718f540
          curl -s https://2m.statict.cn/ren?fqdn=haoshenict.2m.pub&t=47456ebb542ebfe4847419f85e129159
