name: Take it easy

# You know that?
# The first commit was fdf1479.
# Donate on afdian.net: https://afdian.net/@xiaozhu2021
on:
  push:
    branches:
      - master
  workflow_dispatch:
  schedule:
    - cron: '*/10 */2 * * 1-5'

jobs:
  auto:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Generate README.md
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: |
          git pull origin master
          echo "Now the time is $(date +"%Y-%m-%d %H:%M:%S %P")" > README.md
          echo -e "\n---\n" >> README.md
          echo -e "<small>$RANDOM$RANDOM$RANDOM$RANDOM$RANDOM$RANDOM$RANDOM</small>\n" >> README.md
          echo -e "\`\`\`txt\n" >> README.md
          echo -e "Latest commit SHA is: ${GITHUB_SHA}" >> README.md
          echo -e "\`\`\`" >> README.md
          echo [SUCCESS] README.md is OK now!
          echo -e "$(date +"%Y-%m-%d %H:%M:%S")" > time.txt
          echo [SUCCESS] time.txt is OK now!

      - name: Commit and Push
        run: |
          git config --global user.email "${GITHUB_ACTOR}@users.noreply.github.com"
          git config --global user.name "${GITHUB_ACTOR}"
          git add .
          git commit -m ":star: Update time"
          git push origin master
